---
- name: Create /ibmdata/htdocs directory root:root

- name: Install apache httpd

- name: Configure seport to listen on tcp 8080 and 8443 using community.general.seport



- name: Enable httpd to start at boot

- name: Open firewall ports 8080 & 8443

- name: Create /var/log/httpd directory owned by root:root with 0750 permissions

- name: Create httpd.conf from a template and save as /etc/httpd/conf/httpd.conf

- name: Start httpd



- name: Create index.html from a template and save it as /ibmdata/htdocs/index.html owned by apache:apache

- name: Set SELinux to Permissive
