---
  - name: IBM MQ Management
    hosts: mqservers

    tasks:

      - name: Create mqm group
        ansible.builtin.group:
          name: mqm
          state: present

      - name: Create mqm user
        ansible.builtin.user:
          name: mqm
          group: mqm
          state: present

      - name: Set MQ environment variables through profile
        ansible.builtin.lineinfile:
          path: /home/ano-user/profile
          line: "{{ _line_ }}"
          state: present

      - name: Set MQ environment variables through profile on RedHat
        ansible.builtin.lineinfile:
          path: /etc/profile.d/mq.sh
          line: "{{ _line_ }}"
          state: present
        vars:
          _line_: export PATH=$PATH:$MQ_HOME/bin

      - name: Create an admin user
        ansible.builtin.command: |-
          mqcpf -a add {{ mq_user }} -f {{ mq_user }}.cpf -u {{ mq_password }} -g mqm -T

      - name: Add 'mqclient' group
        ansible.builtin.group:
          name: mqclient
          state: present

      - name: Add the user 'app' with a specific UID
        ansible.builtin.user:
          name: app
          group: mqclient
          uid: 1000
          state: present
